from .mgfn import *  # noqa
from . import rtfm  # noqa  (triggers MODELS.register("rtfm"))
from . import sultani  # noqa  (triggers MODELS.register("sultani"))
from . import clip_tsa  # noqa  (triggers MODELS.register("clip_tsa"))
from . import ur_dmu  # noqa  (triggers MODELS.register("ur_dmu"))
from . import vadclip  # noqa  (triggers MODELS.register("vadclip"))
from . import gs_moe  # noqa  (triggers MODELS.register("gs_moe"))
from . import tpwng  # noqa  (triggers MODELS.register("tpwng"))
from . import s3r  # noqa  (triggers MODELS.register("s3r"))
from . import bn_wvad  # noqa  (triggers MODELS.register("bn_wvad"))
from . import pel4vad  # noqa  (triggers MODELS.register("pel4vad"))
